### PR TITLE
#9 - parameterized generation of docker images

### PR DESCRIPTION
**Pull request by jpahullo**
This PR will contain the patch, starting from #8, to enable parameterized generation of docker images.

### CODE REVIEW

**Comment by jpahullo** [comment]
@amato-gianluca , this PR is ready to be checked for you and merge if you consider so.

Thanks for your time.

Jordi

**Comment by jpahullo** [comment]
I rebased the branch with the latest master version. It is ready to check and merge, if you like, @amato-gianluca 

Thanks

**Comment by amato-gianluca** [comment]
I am planning to merge this PR.

Just one question. Is it really needed to pass all these  locale related attributes ? Is it not enough to pass the LANG variable ?

**Comment by jpahullo** [comment]
Hi @amato-gianluca ,

Sincerely, I do not remember now why I put all the environment variables so time ago when I worked on generating the WIMS image for our institution. I remember looking for it, since I first tried it with Catalan, and these days working on this again, I replaced them with English. I cannot see a comment telling me why I put them all. 

Also, I do not remember, but they were necessary to work properly either the interpretation of WIMS help pages and also commands being executed by WIMS. I remember this, but not found any comment explaining why and so.

If you like, I can try simplifying it to using just the LANG variable in the compile and environment variables within the Dockerfile, to check its results and I will be back with that.

Apart from that, that may seem ugly in appearence on the code, it works like a charm. So, I proposo you to consider accept this PR as is, and I will open a new issue an PR to try to simplify LANG-related variables.

What do you think?

Thanks a lot,

Jordi

**Comment by amato-gianluca** [comment]
Fine! 

And thanks to you for all these upgrades.

Gianluca

**Pull request merged**
