### PR TITLE
 #15 - make docker image generation extensible and sustainable

### LINKED ISSUE #15: proposal for extensible and sustainable WIMS docker image
Hi @amato-gianluca ,

I am facing the building of a production-ready version of the WIMS docker image, based on your work.

I am having clear which is need for that, at least some requirements right now, to get it extensible and sustainable. Let me explain:

1. Extensible entrypoint.sh
   1. I see that I need to customize what is done inside the entrypoint.sh. The current version is awesome for a local testing.
   2. But for our production infrastructure, I need to customize ssmtp settings, and other things.
   3. So, the idea is to make it possible that anyone, cloning this repo, could customize entrypoint things, without much effort.
   4. This is a win-win: win for this repo, so it is more sustainable and extensible, and win for others that would like to use this repo for having WIMS ready. And probably, would make it possible to receive further contributions.
2. Extensible Dockerfile
   1. Your dockerfile is fantastic.
   2. And I identified the needs to customize apache settings, directories and config files to be aligned on our production environment.
   3. So the idea is to have some bash script, that maybe in this repo may be empty or having a minimal task, so that any one cloning this repo could customize the WIMS image without much effort.

Would you like to receive such a PR?

The idea of this would be to produce the necessary folders and flow to get it done, just producing the same result like the current one. No more no less. But it would let me to extend it easily, cloning this repo, customize the produced WIMS docker image.

What do you think?

Thanks in advance,

Jordi

### PR DESCRIPTION
**Pull request by jpahullo**
Closes #15 

This is the proposal for making extensible and sustainable the generation of the WIMS docker image.

Now:

1. entrypoint.sh is a execution of a set of scripts. Each scripts decides when to execute (if only on production environment, only for testing or always). It is all run on the container startup.
2. Dockerfile: provides two extensible points:
   1. Now it is all copies from ./assets/ (from host) into /wims (from image). Any clone of this repo could add new files and get them inside the docker image, transparently, without modifying the definition of the Dockerfile.
   2. There is a post-install.sh script which now runs the same commands as in the before Dockerfile version. But, as with entrypoint.sh, it is again a set of scripts that will be run. 
   3. It is all run during the image generation. So, clones of this repo could execute further scripts (previously copied in the above step), and execute them here.

We will use this in our own WIMS image. We find it very flexible and customizable. By now, we do not identify other points to customize from Dockerfile, so these should be enough.

It is all for your review @amato-gianluca .

Thanks,

Jordi

### CODE REVIEW

**Comment by amato-gianluca** [comment]
Very nice work!

There are a couple of things that needs to be changed. I can make the changes myself after I merge the PR, or you can do them before if you prefer:

1. replace "return" with "exit" in the assets scripts. The command return produces the following errors in the logs: ```return: can only `return' from a function or sourced script``` and does not exit from the script;
2. change  ` "$APP_ENV" != "prod"` with  `"$APP_ENV" == "prod"` in the file `5_add_manager_site_ip.sh`, since this is only meant for test environments.

Let me know how you prefer to proceed.

P.S. Would you like to be added to the maintainer metadata in the Dockerfile ?

**Comment by jpahullo** [comment]
Hi @amato-gianluca ,

You're totally right. I did some trials before uploading changes, and I did not identified both errors.

Later on, I did more trials and I detected both ones. I will update the patch. It may be later than sooner, since I am working on the production-ready image for WIMS service. And I did need to perform some other changes.

Regarding to appear as the co-maintainer: I do think that it is something you can do. I don't think it is quite politely to make a PR including myself as co-maintainer. If you want to do it, I will be very glad. In that case, please use "Jordi Pujol-Ahulló <jordi.pujol@urv.cat>".

Thanks a lot,

Jordi

**Comment by jpahullo** [comment]
Sorry @amato-gianluca , for not updating this PR so that you would get prevented dealing with these bugs.

**Comment by jpahullo** [comment]
Hi @amato-gianluca ,

Finally, I have got to make some checking and I could update this PR just now.

It has the changes you required. I have squashed all changes (sorry). But I thought on making you easy accepting this PR in a single commit.

Thanks,

Jordi

**Comment by amato-gianluca** [comment]
There are still some return in the place of exit, but I am going to merge this PR and change it later.

**Pull request merged**
